# Generated by Django 5.2.9 on 2025-12-03 17:06

import catalog.models.car
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to=catalog.models.car.car_image_upload_path),
        ),
    ]
